markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

title: KF6009
subtitle: Model-based design and verification
authors: David Kendall, Alun Moon
copyyear: 2015-2018
url: http://hesabu.net
baseurl: /kf6009
raurl: /assets/ra
rraurl: /assets/ra
#url: http://localhost:4000
#raurl: http://localhost:4000/assets/ra

lab_links:
  - title: Lab 01
    url: L01.html
    #rep: cm0605_lab01
  - title: Lab 02
    url: L02.html
    #rep: cm0605_lab01
  - title: Lab 03
    url: L03.html
    #rep: cm0605_lab03
  - title: Lab 04
    url: L04.html
    #rep: cm0605_lab01
  - title: Lab 05
    url: L05.html
    #rep: cm0605_lab05
  - title: Lab 06
    url: L06.html
    #rep: cm0605_lab01
  - title: Lab 07
    url: L07.html
    #rep: cm0605_lab07
  - title: Lab 08
    url: L08.html
    #rep: cm0605_lab01
  - title: Lab 09
    url: L09.html
    #rep: cm0605_lab09
  - title: Lab 10
    url: L10.html
    #rep: cm0605_lab01
  - title: Lab 11
    url: L11.html
    #rep: cm0605_lab01
  - title: Lab 12
    url: L12.html
    #rep: cm0605_lab01
 

#right_links:
  #- title: View on GitHub
    #url: https://github.com/davidkendall/cm0604

#repo: https://github.com/davidkendall/cm0604

